### ISSUE TITLE
Lista M3U

### ISSUE THREAD

**Issue by redbuzao** [skyrisk/brazucaplay#11]
Gosto muito desse add-on do Kodi e uso muito no computador. Recentemente comprei um Mi Stick TV e nativamente é possível incluir canais através de lista M3U. Teria algum modo de transformar seu add-on em uma lista M3U?

**Comment by skyrisk** [comment]
Depende do conteúdo, se não forem estáticos como em alguns conteúdos não seria possível.
Canais da RC por exemplo que são links com tokens, não seria possível.

**Comment by redbuzao** [comment]
Quais canais seriam estáticos e quais não?

**Comment by skyrisk** [comment]
Movies da RC, topcanais etc.
Dá muito trabalho listas m3u.
