### ISSUE TITLE
Não executa os canais ao vivo após atualizacao 21.01.2021 na Android box

### ISSUE THREAD

**Issue by epaminondas22** [skyrisk/brazucaplay#15]
Não estou conseguindo assistir os canais ao vivo após a ultima atualização usando o kodi numa android box
Na primeira opção de links (Somente HD), ao selecionar um canal começa a carregar, e quando termina o loading não acontece nada
Na segunda opção até funciona em SD, mas ao tentar trocar de canal trava.

Tentei reinstalar o repositorio e o add-on mas não teve efeito.

**Comment by skyrisk** [comment]
Este problema não há ligação com as atualizações, Tente usar VPN ao conectar para saber se há algum bloqueio no host.
