### ISSUE TITLE
Série sumiu

### ISSUE THREAD

**Issue by xZeroW** [skyrisk/brazucaplay#17]
Assisti uns 4ep de blindspot e agora ele não aparece mais na lista.
Já limpei os dados, reinstalei e nada.
O que eu faço?

**Comment by skyrisk** [comment]
Use o filtro para procurar a série.

**Comment by xZeroW** [comment]
> Use o filtro para procurar a série.

Vlw resolveu
Na lista eu só procurei por blindspot e não ponto cego, pesquisando também achava.
