### ISSUE TITLE
Problema para reproduzir - Rede Canais

### ISSUE THREAD

**Issue by Iceboy-6** [skyrisk/brazucaplay#18]
Olá,  BrazucaPlay, bom dia.

Há algumas semanas estou tentando reproduzir filmes e séries listadas no addon Brazuca Play (Kodi 18.9v, addon 2.1.3). Apesar de conseguir reproduzir as da NetCine, não consigo reproduzir os filmes e séries da Rede Canais.

Aparece o seguinte erro:
"**Resolver** indisponível no momento. Tente novamente - Se o erro continuar pode ser devido a problemas com o **Resolver**"

Ao tentar assistir pelo site da rede canais, funcionou normalmente. Reinstalei o app e os plugins relacionados, porém sem sucesso. 

Saberiam dizer se esse erro já está mapeado por vocês e possuem previsão para solucionar o problema?

Obrigado pelo addon e por todo o esforço à comunidade!

**Comment by skyrisk** [comment]
Boa noite, verifique novamente.

**Comment by Iceboy-6** [comment]
Boa noite, obrigado pelo rápida resposta.

Infelizmente, o mesmo erro persiste. 

Tentei também reinstalando o addon, inclusive o plugin URLResolver, mas o erro apareceu novamente.

Se eu enviasse o log seria de utilidade?

Obrigado.

**Comment by skyrisk** [comment]
Olá Iceboy, esse é um problema com o Cloudflare e que não há possibilidades de contornar.
