### ISSUE TITLE
Uso Indevido dos Videos do RedeCanais

### ISSUE THREAD

**Issue by RedeCanais** [skyrisk/brazucaplay#19]
Ola. percebemos que você vem utilizando nossos vídeos em seu addon por muito tempo de forma indevida. Nos da Equipe RedeCanais não lhe autorizamos a utilizar nossos videos em seu addon.
Por favor remova o conteúdo do RedeCanais do Addon e nao volte a utilizar nosso conteúdo.

Obrigado pela cooperação.

**Comment by RedeCanais** [comment]
O usuarios devem acessar o conteudo do site de forma correta pelo dominio original e oficial: redecanais.re

**Comment by skyrisk** [comment]
Olá, as últimas implementações em seu site quebraram as possibilidades de reproduzir fora dele ao menos sem um navegador real.

Não há com o que se preocupar, tente melhorar o HTML contra "escavadores", talvez com JS.
