### ISSUE TITLE
Opção para desativar controle parental

### ISSUE THREAD

**Issue by coxinhaatomica** [skyrisk/brazucaplay#20]
Eu vi que essa opção ativa os canais adultos com uma senha, gostaria que tivesse outra opção nas configurações que desativasse o controle parental por inteiro, tenho crianças e também não tenho interesse nestas opções, e somente uma sugestão, desculpa incomodar e agradeço muito pelo trabalho de vocês!

**Comment by skyrisk** [comment]
Olá, sua sugestão já foi adicionada nos ajustes. Obrigado!
