### ISSUE TITLE
Não instala na versão 18.5 do Kodi

### ISSUE THREAD

**Issue by victorsferreira** [skyrisk/brazucaplay#5]
Não consigo atualizar o Brazuca na versão 18.5 do Kodi. 

Quando abro o Add-on tem uma mensagem e mais nada:

"Atualize sua versão"

Quando clico, vem a mensagem de erro: Brazuca Play Error, check logs for mor information

**Comment by skyrisk** [comment]
Essa mensagem é apenas um texto informativo, instale o repositório que ele se atualizará sozinho.
