### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Alissonv2** [skyrisk/brazucaplay#8]
Olá skyrisk, não consigo encontrar o site de vocês, nem o grupo do telegram, teria como mandar o link por favor?

**Comment by skyrisk** [comment]
Boa tarde, aqui está um convite.
https://t.me/joinchat/KqLjN1NU2IB6GUa9gGUU1A

**Comment by caiobozato** [comment]
@skyrisk pode gerar um convite pra mim também? Esse acima não funciona.

**Comment by skyrisk** [comment]
Pode acessar pelo link do repositório.

**Comment by caiobozato** [comment]
@skyrisk Onde? Não tem nada no README do repo....

**Comment by skyrisk** [comment]
Procura pelo link do repositório do add-on que você acha.
